### ISSUE TITLE
Get community feedback on the maquette-query API

### ISSUE THREAD

**Issue by johan-gorter** [AFASSoftware/maquette-query#1]
We just created maquette-query to help us unit-test our maquette code at @AFASSoftware. Before we start blogging about it, we are hoping to get some community feedback about the API. Do you use unit-tests? Do you think maquette-query is useful? Are the method-names and documentation clear? Is anything missing?
@HelloZeroNet? @cybrown? @argyleink? @kitsonk? @pdfernhout? Anyone else?

**Comment by argyleink** [comment]
Unit tests are a part of some of my projects yes, in a single library like this I think it's a great idea. Everything I peaked at looked good, no feedback from me other than a ![gif](https://media.giphy.com/media/MFajvi9OlDEWY/giphy.gif)

**Comment by kitsonk** [comment]
Yes, I can see the utility of maquette-query.

We utilise unit tests, and while in a lot of ways we would expect to isolate any render code from the rest of the project, there is still a need to validate that any components do actually "behave" as expected.  We were considering possibly stubbing maquette or using some other mechanism, but I could see this being useful. :+1: 

Thanks for reaching out.

**Comment by cybrown** [comment]
Unfortunately, I've not made (yet) a heavy usage of maquette (nor any kind of vdom library), but anything that can ease testing would let more people consider it as a viable alternative, and demonstrate how vdom may be more flexible than template strings.

Thanks for requesting feedback !

**Comment by HelloZeroNet** [comment]
I have no unit tests and not used maquette-query yet (does it makes sense outside of unit-testing?)

I think the documentation is fine, maybe mappings/working with arrays could use more example. (I was unable to make it work based on http://maquettejs.org/docs/arrays.html, so created my own solution)
